<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>gh-info</AssemblyName>
    <RootNamespace>GhInfo.Cli</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <UserSecretsId>gh-info-cli</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CreativeCoders.Core" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GhInfo.Core\GhInfo.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
